<<<<<<< HEAD
title: Tactile theme
description: Tactile is a theme for GitHub Pages.
show_downloads: true
google_analytics:
=======
>>>>>>> 9e8616958be50b3241f179dfe0f641b7b266d768
theme: jekyll-theme-tactile